### ISSUE TITLE
Hungarian Algorithm usage

### ISSUE THREAD

**Issue by iskim517** [ntopia/icpc-teamnote#9]
내용에 코멘트 달아주세요
1. mat는 1 based로 채우는건가 0 based로 채우는건가?
2. matched에 뭐가 들어가나?
3. 최댓값을 리턴하는가 최솟값을 리턴하는가?

**Comment by ntopia** [comment]
* 1-based
* matched[i] = row i 에서 매칭된 col j
* minimum

**Comment by ntopia** [comment]
원래 예전에 있었던 헝가리안 구현은 버림 왜냐하면 그건 사실 O(n^4) 였기 때문.
저 소스의 원 출처에 가보면 O(n^3) 을 위해선 특별히 뭔가를 더 해야한다고 나와있음.
